name: flutter_uploader_example
description: Demonstrates how to use the flutter_uploader plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^3.0.4
  flutter_local_notifications: ^8.1.1
  flutter_uploader:
    path: ../
  image_picker: ^0.8.3+1
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
